### ISSUE TITLE
Elemental Gearbolt USA

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#48] opened 2022-05-08 16:16 UTC
**Issue**
Wrong/Exploding Polygons in the background

**Reproduce**
Start a new game and you will see it

**Workaround**
none

**BIOS**
7001

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_2

**Comment by RobertPeip** [comment] 2022-06-22 06:59
Exploding polygons are fixed, will downgrade priority

**Comment by Kuba-J** [comment] 2022-06-27 22:20
> And there is another Bug besides of the exploding Polygons. Start a new Game and watch the Intro. At 0:20 a Child speaks but this is a way to Silent. I can be barely heard. Compare here at around 0:20 https://www.youtube.com/watch?v=zdY4676b3gI

Intro works very well, voice , speech also , everything identical to the real PlayStation. Checked with core beta PSX_DualSDRAM20220627.rbf - https://youtu.be/NTtnKFBJxiU

**Comment by RobertPeip** [comment] 2022-06-28 03:59
I will test this myself later today. If i also hear the child clearly i will close it

**Comment by Atmosfear1968** [comment] 2022-06-28 10:40
Can be closed. Works flawlessly. The core wasn't the problem. A cheap Chinese HDMI audio extractor was the cause of the sound problem. Replaced it and everything was fine. Strange that it did only affect the Soundvolume of the Child speaking.

**Closed** 2022-06-28 13:29 UTC
Labels: Priority-3
