### ISSUE TITLE
Corrupted lines over HDMI when system switches resolutions

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/PSX_MiSTer#87] opened 2022-05-11 18:07 UTC
Over HDMI, corrupted lines can be seen for a very brief moment whenever the system changes resolution.

This can be noticed at the end of the bios boot after the PlayStation logo fades out, or in games such as Chrono Cross whenever closing the menu.

Can this be fixed even?

PlayStation  bootup (on fade out):
![IMG_4703](https://user-images.githubusercontent.com/86253908/167917063-73ee420f-1d2f-42d5-9ad8-7c81c7c7b86a.jpg)

Chrono Cross:
(Get into the game, when possible press Triangle to open the menu screen, then exit back out):

![IMG_4705](https://user-images.githubusercontent.com/86253908/167917108-2ecd26c4-975a-403d-941b-a80f13633def.jpg)

**Comment by Fuzzybane** [comment] 2022-05-11 18:53
what video mode and vsync adjust are you using? I don't get this and I been testing for months

**Comment by AtomicShroom** [comment] 2022-05-11 19:02
video_mode=0
vsync_adjust=0
vscale_mode=2

**Comment by Fuzzybane** [comment] 2022-05-11 19:20
ohhh ok the PSX logo to game I am pretty sure happens on hardware

**Comment by Fuzzybane** [comment] 2022-05-11 19:25
so yeah this is not a bug and doubt it can be fixed

**Comment by Fuzzybane** [comment] 2022-05-11 20:01
ok I see that also in the core, but not in that video, are we sure that he is using original hardware in that video?

**Comment by Fuzzybane** [comment] 2022-05-11 20:01
it doesn't look as bad as yours for me though

**Comment by birdybro** [comment] 2022-05-11 20:53
The menu transitions don't do this on original hardware for Chrono Cross, but they do happen in the core, yes. However, the screen transition tiny flicker of corruption is due to the scaler changing how it outputs a resolution, it has to adjust in real time, it's not instant or perfect. This same thing happens with 240p test suite with interlaced video switching rapidly on other cores. It also happens (but more briefly) when you switch your scaling methods in the cores in the OSD for other cores.

For this to be fixed it would be something changed in https://github.com/MiSTer-devel/Template_MiSTer most likely. This isn't an issue with the PSX core AFAICT.

**Comment by sorgelig** [comment] 2022-05-11 22:28
That's not a core specific as told above and well known problem which is hard to fix.
It will be fixed when it will be possible.

**Closed by sorgelig** 2022-05-11 22:28 UTC

**Comment by sorgelig** [comment] 2022-05-11 22:32
Btw, this problem is not even MiSTer specific. 
Many TVs and Monitors shutdown the video for some time when resolution changes on HDMI/DP. Some displays do it quickly, some displays need several seconds for video to appear. MiSTer does it without turning off the video and as soon as possible, so it's just different ways to handle resolution change. And i think it's not as bad as many TVs.
