### ISSUE TITLE
Ray tracers grafic issues starting stage two

### ISSUE THREAD

**Issue by hardyhell** [MiSTer-devel/PSX_MiSTer#239] opened 2023-02-04 22:36 UTC
Hy. 

Ray tracers is having texture holes on the track and wrong displayed text like when you end or start a race.

**Comment by Kuba-J** [comment] 2023-02-05 08:59
Hi, what holes? Post some picture , video or post a save state. Flickering and fading of ambient textures in this game also occurs on real hardware. Are you using the default settings?

**Comment by Kuba-J** [comment] 2023-02-05 09:03
JAP. USA or EUR game version ?

**Comment by Kuba-J** [comment] 2023-02-05 10:14
I checked stage 2 , the game works, behaves and looks exactly the same as on real hardware. Flickering and fading road textures is quite a normal thing, such things also occur in other games. I don't see any errors when it comes to text. 

Core:

![IMG_20230205_105623](https://user-images.githubusercontent.com/95412885/216813183-566d7c71-d744-40a9-bf38-34977da591b1.jpg)

PlayStation:

![IMG_20230205_110639](https://user-images.githubusercontent.com/95412885/216813205-37080257-bc3a-4ed9-93eb-23e891f61da1.jpg)

**Comment by RobertPeip** [comment] 2023-02-05 10:31
same here, US version, latest core. works fine:

![grafik](https://user-images.githubusercontent.com/53250236/216813889-4955bb11-d138-42c0-bc16-25c94a34eb2b.png)

**Comment by hardyhell** [comment] 2023-02-05 13:30
Will try to take pics tonight. Played USA version I guess. Think I have enabled something that smoothed the textures. Because they did not look as shitty as on the real ps1. I played mister on a crt

**Comment by Kuba-J** [comment] 2023-02-05 13:46
As you can see above two people have checked your 
issue and the game works fine, it works just like on real hardware. Why don't you write what settings you are using, what version of the core? etc. Please check your setup first.

**Comment by hardyhell** [comment] 2023-02-05 21:28
Psx v230114
Please tell me which settings you want to know. There are a ton of

**Comment by hardyhell** [comment] 2023-02-05 21:39
![Uploading 757780BC-E6DB-4F63-9E4F-133A615B4D22.jpeg…]()

**Comment by hardyhell** [comment] 2023-02-05 21:40
![F080DE03-3FD6-42C2-8FCB-1A4C3467A35E](https://user-images.githubusercontent.com/67065367/216847606-c5bf0f5e-cf95-47d5-b2af-16fffac1eed0.jpeg)


Here. End of stage 2

**Comment by Kuba-J** [comment] 2023-02-05 21:42
I don't need your settings , try with default setting , don't use turbo and other hacks

**Comment by Kuba-J** [comment] 2023-02-05 21:56
Cannot reproduce , works fine here 
![IMG_20230205_225356](https://user-images.githubusercontent.com/95412885/216848232-54d0e00a-8d49-4a3d-8cd5-2e656da54fcd.jpg)

**Comment by Kuba-J** [comment] 2023-02-05 22:12
Are you using bin/cue or chd? do you have the game from a good verified source?

**Comment by hardyhell** [comment] 2023-02-06 12:34
![035DDF4A-1BAB-4BCF-9BC9-1E8B12B2B6FF](https://user-images.githubusercontent.com/67065367/216972438-1f35128f-e8e1-43bc-bd14-d74201369732.jpeg)

seems to be the cd speed. Looking like 6x and faster causes this problem with the mission complete text here.

**Comment by Kuba-J** [comment] 2023-02-06 13:00
So you've found the cause of your problem, (great!) it's not a bug in the core, speed hack is an UNSAFE option, so it doesn't have to work with every game ( and it won't ) , before reporting a bug you should always check the game with default settings. Otherwise there is no point in reporting it.  

Please close the issue.

**Comment by hardyhell** [comment] 2023-02-06 13:39
No wait a second. 
![90FD5552-66EE-4642-8292-E4CF5C441723](https://user-images.githubusercontent.com/67065367/216985718-2d764e59-ec20-4422-a3b6-15962fc2531c.jpeg)

Is this normal too. Default settings and also the time extend text is broken throughout stage 3 with default settings.

**Comment by Kuba-J** [comment] 2023-02-06 13:48
Looks fine here, start game from the beginnig with default settings

![Uploading IMG_20230206_144643.jpg…]()

**Comment by Kuba-J** [comment] 2023-02-06 14:31
And here is video,

[Ray Tracers](https://youtu.be/Er23VKGMXVs) 

Core 20230114, Ray Tracers USA , all settings default,

Verifed redump, bin/cue format

**Comment by hardyhell** [comment] 2023-02-06 14:33
Yes have bin cue format USA version. Capsule collection archive org

same core version as you have

**Comment by hardyhell** [comment] 2023-02-06 14:34
Looks fine for you indeed. Will test again tonight

**Comment by hardyhell** [comment] 2023-02-07 15:56
Played the game all the way from start to final stage. No errors seen with default setting from start of the game. Sorry about the wrong bug then. Seems to be connected to cd speed option. Thanks

**Comment by Kuba-J** [comment] 2023-02-07 16:04
Thanks for the info and good that it works for you!

Greetings!

**Comment by hardyhell** [comment] 2023-02-07 16:34
Thanks for the support.

best wishes 

Bernhard

**Closed** 2023-02-07 18:00 UTC
