### ISSUE TITLE
Worms World Party (USA) (En,Fr,De,Es,It,Nl,Sv,Da)

### ISSUE THREAD

**Issue by Vospi** [MiSTer-devel/PSX_MiSTer#121] opened 2022-05-27 15:18 UTC
**Issue**
At some point during a match (in a specific mission or mode, read ahead) there's a big gap of silence with a click where all the music stops, worms' sounds don't appear to stop. I tested the savestate with and without enhancements (namely fast seek and CD cache), same.

The music just restarts later. It's unclear to me if that happens regularly, one may want to test it if there's a long enough mission available.

I've tested only a specific mission depicted in the savestate, didn't happen to me elsewhere like in a regular multiplayer game. Didn't test with the other missions.

**Reproduce** 
Option 1) Load one of the savestates I provided, wait as described above.
Option 2) Launch Mission mode, pick Mission 1 (called Good Ship Armageddon). Keep playing for about I would say 2 minutes without losing or winning the match. Mission 2 didn't exhibit the bug, so it *might* depend on the music track (which is different there, but the mission is literally too short to tell).

**BIOS** 7001

**CD Image**
Redump bin/cue

**Core Version** 
MiSTer v220524
PSX v220518

[Worms World Party (USA) (En,Fr,De,Es,It,Nl,Sv,Da)_2.zip](https://github.com/MiSTer-devel/PSX_MiSTer/files/8786715/Worms.World.Party.USA.En.Fr.De.Es.It.Nl.Sv.Da._2.zip)

**Comment by Kuba-J** [comment] 2022-11-06 19:17
Please retest

But don't use the savestate you posted here, start from the beginning. I can't reproduce this isse with a new game and new test core 20221106

**Comment by Kuba-J** [comment] 2022-11-06 22:00
This is not a bug in the core , the same thing happens on the real PSX, I checked it a while ago , a repetitive thing after the same amount of time , no matter what the player does ,please close the issue.

**Comment by RobertPeip** [comment] 2022-11-07 04:55
tTanks a lot for testing it!

**Closed by RobertPeip** 2022-11-07 04:55 UTC
Labels: Priority-3
