### ISSUE TITLE
Audio clicking / pop at the start of a CD track.

### ISSUE THREAD

**Issue by HardwareBreaker** [MiSTer-devel/PSX_MiSTer#223] opened 2023-01-12 17:12 UTC
I've been experiencing audio clicking at the start of CD audio tracks

Video example below:

https://streamable.com/m27ebv (Headphones recommended)

I have tried various options including a full reset. 
CHD or BIN/CUE doesn't seem to alter things either.

I've checked some videos on Youtube and as far as I can tell this has been a potential issue for a long time.

Bonus bug, if you go into the screen adjustment in Ridge Racer Turbo and move the screen down enough the game
will lock up.

**Comment by HardwareBreaker** [comment] 2023-01-12 17:18
> How are you recording this audio? Is it through the analog io's 3.5mm audio jack? If so, that output is highly susceptible to any kind of interference and is known to make noises whenever the FPGA accesses the MicroSD through HPS.
> 
> If not, pretty interesting and would require someone to help test against real hardware to confirm whether it's a bug or not.

HDMI into a capture card. I've also seen people talking about a similar issue with PC Engine and Mega CD.

**Comment by Kuba-J** [comment] 2023-01-12 18:34
On real hardware these clicks do not occur, I checked on the same TV. I checked with the original disc and with PSIO. If this also occurs on other systems with CD then this seems to be a general problem.

**Comment by HardwareBreaker** [comment] 2023-01-12 18:39
> On real hardware these clicks do not occur, I checked on the same TV. I checked with the original disc and with PSIO. If this also occurs on other systems with CD then this seems to be a general problem.

Could be, but I haven't investigated the other systems much.

I did check this video which is original hardware via OSSC. https://youtu.be/tDjsKrUXKAg

No audio clicks I can detect at the start of CD tracks.

**Comment by Kuba-J** [comment] 2023-01-12 18:50
Bug with screen adjust on Ridge Racer Hi-Spec  confirmed

**Comment by RobertPeip** [comment] 2023-01-12 19:53
Anyone interested to provide a savestate close to a reproducible click?

**Comment by Kuba-J** [comment] 2023-01-12 19:59
This occurs before every audio track, even in the audio player (bios)

**Comment by RobertPeip** [comment] 2023-01-12 20:02
ok, got one, will look after it the next days

**Comment by RobertPeip** [comment] 2023-01-13 16:59
general pop issue is fixed now.

RR Turbo still has it, because the commonly available redump image has RIFF headers inside the audible data, which is either a issue with the rip from redump or the original disc.

Normal RR is working fine now. Tested Rayman in BIOS player as well. Both are ok now and have popping sounds in previous version. Therefore i will close this.

**Closed by RobertPeip** 2023-01-13 16:59 UTC

**Comment by HardwareBreaker** [comment] 2023-01-13 17:58
> general pop issue is fixed now.
> 
> RR Turbo still has it, because the commonly available redump image has RIFF headers inside the audible data, which is either a issue with the rip from redump or the original disc.
> 
> Normal RR is working fine now. Tested Rayman in BIOS player as well. Both are ok now and have popping sounds in previous version. Therefore i will close this.

I checked the EU and JP versions and they don't seem to exhibit the click as far as I can tell,
so it seems it is something to do with the dump or original US release.

Ridge Racer - High Spec Ver. & Namco Catalogue '98 (Japan) (R4 + JogCon)
Ridge Racer Hi-Spec Demo (Europe)

The Adjust Screen option locks up the core in those releases too.
