### ISSUE TITLE
Spyro Year of the Dragon (USA): Rare random freezing and EA error when opening OSD with Autosave on.

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/PSX_MiSTer#98] opened 2022-05-16 12:56 UTC
This is very rare and has occurred to me only twice over multiple hours of playing Spyro: Year of the Dragon.

Occasionally the game will hang when opening the OSD with Autosave activated, followed shortly by an EA (SPU Timeout) error.  When this happens, you'll also find that the Memory Card was not saved.

Haven't been able to find a consistent way of reproducing it.

**Comment by AtomicShroom** [comment] 2022-05-16 17:05
I'd have to guess it's related to something the PSX core does, because I've never, ever had that occur in any other core before. Whatever the case, I'm sure we'd all appreciate the common act of opening the OSD to not be a Russian roulette. :)

That said I'd very much doubt Spyro 3 is the only game where this can happen.  Hopefully more people will encounter it elsewhere and maybe find commonalities that point to possible reproduction methods.

**Comment by AtomicShroom** [comment] 2022-05-16 21:46
I’ve been able to reproduce it a few more times. Seems to happen if you open the OSD (triggering a Memory Card save operation) just ~1 second after the music starts playing when entering a level or back to the world hub. 

Steps to repro:
1. Enter a level.
2. After entering and ~1 second after the music starts playing, open the OSD.
3. If it didn’t crash, pause and exit the level.
4. After entering the hub world and ~1 second after the music starts playing, open the OSD. 
5. If it didn’t crash, re-enter the level and repeat steps 2-5 until you get the crash.

Takes me around 5 to 30 times every time, but I end up getting it pretty consistently. For reference, this is the exact camera angle on which it crashed when the camera rotates around Spyro after returning to the hub world:

![79A2ED75-0BDC-4BED-8977-CA1B69A06DF5](https://user-images.githubusercontent.com/86253908/168687658-2c8da378-c2a7-4d7c-9633-ba5cd0bd3240.jpeg)

**Comment by birdybro** [comment] 2022-05-16 22:31
This is currently known behavior. If the CD is busy and you open the OSD it can cause timing issues with the core and communicating to the CD image. Spyro probably happens to be much more sensitive to it than other games.

The reason it hasn't happened to you in other cores is because other cores aren't based on a system that has a super sensitive cd-rom timing that is tied into other components in a very sensitive way. The upcoming Saturn core might see similar difficulties in some games, I suppose.

**Comment by RobertPeip** [comment] 2022-05-28 08:48
Hopefully this is fixed with the recent changes. If you can, please try the unstable nightly or testbuild from discord.

**Comment by AtomicShroom** [comment] 2022-05-28 17:03
@RobertPeip : Awesome! I’ll test it out when I get a chance! Do I need the latest main build as well, or just the core alone will do?

**Comment by Fuzzybane** [comment] 2022-05-28 19:19
you need latest unstable main as well :)

**Comment by AtomicShroom** [comment] 2022-05-29 14:25
Unfortunately I was able to reproduce the hang using PSX_unstable_20220528_081a70.rbf and MiSTer_unstable_20220527_14b06d.

**Comment by RobertPeip** [comment] 2022-05-30 04:09
Can you please test if the hang also happens if you turn off autosave and just open the OSD with version 05 28?
Need to know if the saving is the issue or the pausing.

**Comment by AtomicShroom** [comment] 2022-05-30 21:11
> Can you please test if the hang also happens if you turn off autosave and just open the OSD with version 05 28?
> Need to know if the saving is the issue or the pausing.

I’ve tried well over 100 times and I’ve been unable to reproduce it with Autosave turned off.

**Comment by RobertPeip** [comment] 2022-05-31 10:10
very good thank you, so i can focus on the saving when i have time.

**Comment by RobertPeip** [comment] 2022-06-24 14:38
Could reproduce the issue and made a fix for it. You can try the testbuild on discord or wait for unstable nightly to check if you want.

**Comment by AtomicShroom** [comment] 2022-06-24 19:42
Tried well over 100 times with PSX_unstable_20220624_14eba5.rbf and I was not able to reproduce it! Seems fixed!! 👍🥳👏

**Comment by RobertPeip** [comment] 2022-06-25 06:00
Thanks a lot for verifying! Will close it.

**Closed by RobertPeip** 2022-06-25 06:00 UTC
Labels: Priority-2
