### ISSUE TITLE
Toaplan Shooting Battle 1 JAPAN

### ISSUE THREAD

**Issue by Fuzzybane** [MiSTer-devel/PSX_MiSTer#56] opened 2022-05-08 22:08 UTC
**Issue**
PSX Bios Logo Interlacing in background

**Reproduce**
Boot game, after the Banpresto logo you will see it

**Workaround**
none

**BIOS**
7000

**CD Image**
Redump bin/cue

**Core Version**
PSX_DUALSDRAM20220508_3

**Comment by blisstik** [comment] 2022-07-23 20:03
This seems to be fixed now. I don't see any flickers using LCD and vsync=0

**Comment by Fuzzybane** [comment] 2022-07-30 17:05
closing as per blisstik saying it is fixed

**Comment by Fuzzybane** [comment] 2022-07-30 17:58
works for some and not for others, it is a minor issue though

**Comment by mapfde** [comment] 2022-08-02 13:57
Tried it with the SingleSDRAM version, and could reproduce the issue, but only on the digital output.

Checked multiple times, with both vsync_adjust=0 and 1.

BIOS: whatever update_all downloads
CD Image: Redump CHD
Core version: PSX_unstable_20220801_19f379.rbf

Display: Sony CRT on analog and DVI LCD 1600x1200

**Comment by blisstik** [comment] 2022-11-04 22:56
Still exists PSX_DualSDRAM20221102.rbf

**Comment by RobertPeip** [comment] 2022-11-09 15:44
I only see normal 480i<->240p switch garbage from scaler here.

I don't think it's a game specific issue.

**Comment by wwark** [comment] 2022-11-09 16:18
still occured on my side.
The logo of toaplan is not well print on the screen and a brief flash of the Playstation logo.

**Comment by RobertPeip** [comment] 2022-11-20 08:58
This logo screen is using a odd 255i mode that maybe the scaler cannot handle and this mode shouldn't be used either.
Using fixed VBlank = on fixes the issue, as it uses standard 480i.

Fixed Vblank = On will act like the viewport of a CRT and is therefore the correct version.
Fixed Vblank = Off is mainly there, because many games show black bars all around the image otherwise on modern screens

We could implement other workarounds for such odd resolutions, but it's not useful as fixed Vblank already exists.
I will therefore close the issue.

![grafik](https://user-images.githubusercontent.com/53250236/202893543-bb3086eb-2763-4b62-86c7-74f31ec73aa1.png)

**Closed by RobertPeip** 2022-11-20 08:58 UTC
Labels: Priority-3

**Comment by wwark** [comment] 2022-11-20 11:57
thank you I will activate this mode for this game
