### ISSUE TITLE
Parappa [NTSC-U] graphic frozen while sound continues

### ISSUE THREAD

**Issue by Videodr0me** [MiSTer-devel/PSX_MiSTer#130] opened 2022-06-04 22:09 UTC
Playing Parappa I noticed two freezes, which i never encountered on real hardware:

(1) Graphics frozen in the drivers licence stage, music continues playing. Button presses seem to register. After about 30 seconds graphics recover and game runs normally.

(2) One freeze at the retry screen, this one did not recover after waiting a minute or so, I had to reload the disc.

These two freezes occured during a 60 minute play session. Unfortunately these are not easily reproducable.

Core: PSX20220511
Disc: Redump

**Comment by Fuzzybane** [comment] 2022-07-23 17:49
cannot reproduce this with todays build, can you retest please?

**Comment by RobertPeip** [comment] 2022-08-26 15:08
Please retest with new testbuild

**Comment by Fuzzybane** [comment] 2022-08-26 16:08
still cannot reproduce please close :)

**Comment by Fuzzybane** [comment] 2022-08-27 16:58
@Videodr0me can you please close this issue?

**Closed** 2022-08-28 18:24 UTC
Labels: Priority-1, Please Retest
